### ISSUE TITLE
BUG - Java doc is not deploying

### ISSUE THREAD

**Issue by lucapl** [lucapl/TextTransformer#42]
Java doc is not deploying
https://github.com/lucapl/TextTransformer/actions/runs/5039393478/jobs/9037504230

![image](https://github.com/lucapl/TextTransformer/assets/107052397/3e703af1-a47b-4696-880b-2f5e91636a63)

**Comment by ErykWalter** [comment]
check out this one: https://stackoverflow.com/questions/72851548/permission-denied-to-github-actionsbot
you have to change the permissions for GITHUB_TOKEN in github actions settings

**Comment by lucapl** [comment]
yup, changing permissions fixed it
